// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6y76FFUHIrAP6ErCsC1acA4NX7H-tp0I',
    appId: '1:142468233766:web:80bad1751fa25640f9c4e7',
    messagingSenderId: '142468233766',
    projectId: 'autopecas-d1c3c',
    authDomain: 'autopecas-d1c3c.firebaseapp.com',
    storageBucket: 'autopecas-d1c3c.firebasestorage.app',
    measurementId: 'G-XZNEXCEYT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxm0NHCOE6hTSjx9ds2ZhPs5Z4PKyPJm8',
    appId: '1:142468233766:android:257889fd863407a4f9c4e7',
    messagingSenderId: '142468233766',
    projectId: 'autopecas-d1c3c',
    storageBucket: 'autopecas-d1c3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKjP_qjyMJVZN99BcmiSZCIFxk3mB6Wow',
    appId: '1:142468233766:ios:6855100a19a893abf9c4e7',
    messagingSenderId: '142468233766',
    projectId: 'autopecas-d1c3c',
    storageBucket: 'autopecas-d1c3c.firebasestorage.app',
    iosClientId: '142468233766-9ksme58dskmp8vdgtistrf6ciie84utn.apps.googleusercontent.com',
    iosBundleId: 'com.example.autopecas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKjP_qjyMJVZN99BcmiSZCIFxk3mB6Wow',
    appId: '1:142468233766:ios:6855100a19a893abf9c4e7',
    messagingSenderId: '142468233766',
    projectId: 'autopecas-d1c3c',
    storageBucket: 'autopecas-d1c3c.firebasestorage.app',
    iosClientId: '142468233766-9ksme58dskmp8vdgtistrf6ciie84utn.apps.googleusercontent.com',
    iosBundleId: 'com.example.autopecas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6y76FFUHIrAP6ErCsC1acA4NX7H-tp0I',
    appId: '1:142468233766:web:9bd9c0bb79ad7c74f9c4e7',
    messagingSenderId: '142468233766',
    projectId: 'autopecas-d1c3c',
    authDomain: 'autopecas-d1c3c.firebaseapp.com',
    storageBucket: 'autopecas-d1c3c.firebasestorage.app',
    measurementId: 'G-TQBYD2ZPSL',
  );
}
